spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma
    username: maximkim
    password: feeling
    platform: posrgesql
    driver-class-name: org.postgresql.Driver


